flowchart TD
  ganrob[Current Repository Structure] --> Pi
  ganrob --> Arduino

  Pi --> B(piGantry)
  B --> imageProcess
  B --> piSerial

  subgraph piSerial [piSerial module]
  E([serialInter.py]) --> F
  F([TkInterUI.py]) --> E
  end

  subgraph imageProcess [imageProcess module]
  G(Not started)
  end

  E --> loco
  Arduino --> loco([arduinoMotor.ino])
  loco --> E


